# 馬連BOX戦略設定
data_path: "tsv/predicted_results_all.tsv"
strategy_name: "box_quinella"
strategy_params:
  top_n: 3

fund_manager_name: "fixed"
fund_manager_params:
  bet_amount: 300

initial_fund: 100000
